[versions]
android-compile = "35"
android-min = "21"
atomicfu = "0.27.0"
coroutines = "1.10.1"
jvm-toolchain = "11"
kotlin = "2.1.20"
tuulbox = "8.0.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.15.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.2" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "3.19.2" }
jna = { module = "net.java.dev.jna:jna", version = "5.17.0" }
khronicle = { module = "com.juul.khronicle:khronicle-core", version = "0.5.1" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.7.0" }
mockk = { module = "io.mockk:mockk", version = "1.13.17" }
robolectric = { module = "org.robolectric:robolectric", version = "4.14.1" }
tuulbox-collections = { module = "com.juul.tuulbox:collections", version.ref = "tuulbox" }
tuulbox-coroutines = { module = "com.juul.tuulbox:coroutines", version.ref = "tuulbox" }
wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version = "2025.4.3" }
wrappers-web = { module = "org.jetbrains.kotlin-wrappers:kotlin-web" }

[plugins]
android-library = { id = "com.android.library", version = "8.8.1" }
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.17.0" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.0.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
