[versions]
android-compile = "34"
android-min = "21"
atomicfu = "0.23.1"
coroutines = "1.7.3"
jvm-toolchain = "11"
kotlin = "1.9.22"
tuulbox = "7.0.1"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
tuulbox-collections = { module = "com.juul.tuulbox:collections", version.ref = "tuulbox" }
tuulbox-coroutines = { module = "com.juul.tuulbox:coroutines", version.ref = "tuulbox" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version.ref = "tuulbox" }
uuid = { module = "com.benasher44:uuid", version = "0.8.2" }

[plugins]
android-library = { id = "com.android.library", version = "8.2.1" }
atomicfu = { id = "kotlinx-atomicfu", version.ref = "atomicfu" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.10" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.1.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.26.0" }
validator = { id = "binary-compatibility-validator", version = "0.13.0" }
