[versions]
android-compile = "34"
android-min = "21"
atomicfu = "0.26.1"
coroutines = "1.9.0"
jvm-toolchain = "11"
kotlin = "2.0.21"
tuulbox = "8.0.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.15.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.1" }
khronicle = { module = "com.juul.khronicle:khronicle-core", version = "0.5.0" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.6.0" }
tuulbox-collections = { module = "com.juul.tuulbox:collections", version.ref = "tuulbox" }
tuulbox-coroutines = { module = "com.juul.tuulbox:coroutines", version.ref = "tuulbox" }
wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version = "1.0.0-pre.835" }
wrappers-web = { module = "org.jetbrains.kotlin-wrappers:kotlin-web" }

[plugins]
android-library = { id = "com.android.library", version = "8.7.3" }
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.17.0" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.4.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
