[versions]
android-compile = "35"
android-min = "21"
atomicfu = "0.29.0"
coroutines = "1.10.2"
jna = "5.18.1"
jvm-toolchain = "17"
kotlin = "2.2.21"
tuulbox = "8.1.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "4.2.5" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
khronicle = { module = "com.juul.khronicle:khronicle-core", version = "0.6.0" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version = "0.5.0" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.0" }
mockk = { module = "io.mockk:mockk", version = "1.14.9" }
robolectric = { module = "org.robolectric:robolectric", version = "4.16.1" }
tomlkt = { module = "net.peanuuutz.tomlkt:tomlkt", version = "0.5.0" }
tuulbox-collections = { module = "com.juul.tuulbox:collections", version.ref = "tuulbox" }
tuulbox-coroutines = { module = "com.juul.tuulbox:coroutines", version.ref = "tuulbox" }
wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version = "2025.12.6" }
wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser" }
wrappers-web = { module = "org.jetbrains.kotlin-wrappers:kotlin-web" }

[plugins]
android-library = { id = "com.android.library", version = "8.13.0" }
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.2.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
